Update @orb.yml

diff --git a/src/@orb.yml b/src/@orb.yml
--- a/src/@orb.yml
+++ b/src/@orb.yml
@@ -1,15 +1,45 @@
 version: 2.1
 
-description: >
-  Sample orb description
-# What will your orb allow users to accomplish?
-# Descriptions should be short, simple, and informative.
+description: Run commands with Retry
 
 # This information will be displayed in the orb registry and is not mandatory.
 display:
-  home_url: "https://www.example.com/docs"
-  source_url: "https://www.github.com/<organization>/<project-name>"
+  source_url: "https://github.com/ostk0069/retry-command"
 
-# If your orb requires other orbs, you can import them like this. Otherwise remove the "orbs" stanza.
-# orbs:
-#  hello: circleci/hello-build@0.0.5
+commands:
+  run-with-retry:
+    description: Run command with retry
+    parameters:
+      command:
+        description: Command to run
+        type: string
+      retry-count:
+        description: Number of retry 
+        type: integer
+        default: 3
+      sleep:
+        description: Wait duration until next retry
+        type: integer
+        default: 5
+    steps:
+      - run: |
+          retry() {
+             MAX_RETRY=<< parameters.retry-count >>
+             n=0
+             until [ $n -ge $MAX_RETRY ]
+             do
+                "$@"
+                if [ $? -eq 0 ]; then
+                    break
+                else
+                    n=$[$n+1]
+                    sleep << parameters.sleep >>
+                fi
+             done
+             if [ $n -ge $MAX_RETRY ]; then
+               echo "failed: ${@}" >&2
+               exit 1
+             fi
+          }
+          retry << parameters.command >>
+
